import { Item, User, Conversation, Message } from '@/types';

// Tones map to placeholder background colours when rendered without real images.
// picsum.photos provides stable random photos — swap for real product imagery.
const img = (seed: string) => `https://picsum.photos/seed/${seed}/500/750`;

export const MOCK_ITEMS: Item[] = [
  {
    id: 'item-01',
    name: 'Oversize Linen Coat',
    brand: 'Maison Kitsuné',
    price: 340,
    currency: 'AED',
    images: [img('swoon-coat-01')],
    category: 'outerwear',
    subcategory: 'coat',
    colors: ['camel', 'slate', 'bone'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    styleTags: ['minimal', 'editorial', 'linen', 'oversized'],
    material: '100% Linen',
    description: 'Relaxed silhouette with dropped shoulders. Woven from undyed French linen.',
    isActive: true,
  },
  {
    id: 'item-02',
    name: 'Silk Slip Dress',
    brand: 'Atelier Rouje',
    price: 189,
    currency: 'AED',
    images: [img('swoon-dress-02')],
    category: 'dress',
    subcategory: 'slip',
    colors: ['oyster', 'ivory'],
    sizes: ['XS', 'S', 'M', 'L'],
    styleTags: ['minimal', 'elegant', 'silk', 'occasion'],
    material: '100% Silk',
    description: 'Bias-cut slip dress with delicate spaghetti straps and a cowl neckline.',
    isActive: true,
  },
  {
    id: 'item-03',
    name: 'Ribbed Knit Top',
    brand: 'COS',
    price: 79,
    currency: 'AED',
    images: [img('swoon-top-03')],
    category: 'top',
    subcategory: 'knitwear',
    colors: ['bone', 'black', 'sage'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    styleTags: ['minimal', 'basics', 'knitwear', 'casual'],
    material: 'Cotton-Viscose Blend',
    description: 'Fine-knit top with a flattering ribbed texture and a relaxed fit.',
    isActive: true,
  },
  {
    id: 'item-04',
    name: 'Wide-Leg Tailored Trousers',
    brand: 'Toteme',
    price: 285,
    currency: 'AED',
    images: [img('swoon-pants-04')],
    category: 'pants',
    subcategory: 'trousers',
    colors: ['taupe', 'charcoal', 'ivory'],
    sizes: ['XS', 'S', 'M', 'L'],
    styleTags: ['minimal', 'tailored', 'wide-leg', 'office'],
    material: 'Wool-Blend',
    description: 'High-rise wide-leg trousers with a sharp crease and invisible side zip.',
    isActive: true,
  },
  {
    id: 'item-05',
    name: 'Wool Blazer',
    brand: 'Sandro',
    price: 320,
    currency: 'AED',
    images: [img('swoon-blazer-05')],
    category: 'outerwear',
    subcategory: 'blazer',
    colors: ['camel', 'black', 'ivory'],
    sizes: ['XS', 'S', 'M', 'L'],
    styleTags: ['elegant', 'tailored', 'wool', 'office', 'occasion'],
    material: 'Wool',
    description: 'Single-button blazer with notched lapels and a structured silhouette.',
    isActive: true,
  },
  {
    id: 'item-06',
    name: 'Floral Midi Dress',
    brand: 'Ganni',
    price: 165,
    currency: 'AED',
    images: [img('swoon-dress-06')],
    category: 'dress',
    subcategory: 'midi',
    colors: ['blush', 'sage', 'rust'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    styleTags: ['feminine', 'floral', 'casual', 'summer'],
    material: 'Recycled Polyester',
    description: 'Wrap-style midi dress with an all-over floral print and tiered skirt.',
    isActive: true,
  },
  {
    id: 'item-07',
    name: 'Oversized Denim Jacket',
    brand: 'Arket',
    price: 120,
    currency: 'AED',
    images: [img('swoon-denim-07')],
    category: 'outerwear',
    subcategory: 'jacket',
    colors: ['light wash', 'mid wash', 'dark wash'],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    styleTags: ['casual', 'denim', 'oversized', 'basics'],
    material: '100% Cotton Denim',
    description: 'Classic five-pocket denim jacket cut oversized for a relaxed layer.',
    isActive: true,
  },
  {
    id: 'item-08',
    name: 'Broderie Anglaise Blouse',
    brand: 'H&M',
    price: 45,
    currency: 'AED',
    images: [img('swoon-blouse-08')],
    category: 'top',
    subcategory: 'blouse',
    colors: ['white', 'ecru'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    styleTags: ['feminine', 'summer', 'casual', 'boho'],
    material: 'Cotton',
    description: 'Lightweight blouse with delicate broderie anglaise embroidery and puff sleeves.',
    isActive: true,
  },
  {
    id: 'item-09',
    name: 'Cashmere Crewneck',
    brand: 'The Row',
    price: 890,
    currency: 'AED',
    images: [img('swoon-knit-09')],
    category: 'knitwear',
    subcategory: 'sweater',
    colors: ['ivory', 'camel', 'charcoal', 'navy'],
    sizes: ['XS', 'S', 'M', 'L'],
    styleTags: ['minimal', 'luxury', 'cashmere', 'basics'],
    material: '100% Cashmere',
    description: 'Grade-A cashmere crewneck with a classic relaxed fit and ribbed trims.',
    isActive: true,
  },
  {
    id: 'item-10',
    name: 'Printed Mini Skirt',
    brand: 'Zara',
    price: 35,
    currency: 'AED',
    images: [img('swoon-skirt-10')],
    category: 'skirt',
    subcategory: 'mini',
    colors: ['blush', 'sage', 'terracotta'],
    sizes: ['XS', 'S', 'M', 'L'],
    styleTags: ['feminine', 'casual', 'summer', 'print'],
    material: 'Linen-Cotton Blend',
    description: 'Floaty mini skirt with a gathered waistband and abstract botanical print.',
    isActive: true,
  },
  {
    id: 'item-11',
    name: 'Linen Wide-Leg Pants',
    brand: 'Mango',
    price: 69,
    currency: 'AED',
    images: [img('swoon-pants-11')],
    category: 'pants',
    subcategory: 'wide-leg',
    colors: ['ecru', 'khaki', 'black'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    styleTags: ['minimal', 'linen', 'summer', 'casual', 'wide-leg'],
    material: '100% Linen',
    description: 'Flowing wide-leg trousers in 100% linen with an elasticated waist.',
    isActive: true,
  },
  {
    id: 'item-12',
    name: 'Merino Wool Cardigan',
    brand: 'Weekday',
    price: 89,
    currency: 'AED',
    images: [img('swoon-knitwear-12')],
    category: 'knitwear',
    subcategory: 'cardigan',
    colors: ['cream', 'sage', 'rust'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    styleTags: ['casual', 'knitwear', 'layering', 'autumn'],
    material: 'Merino Wool',
    description: 'Oversized button-through cardigan in fine merino wool with drop shoulders.',
    isActive: true,
  },
  {
    id: 'item-13',
    name: 'Satin Bias-Cut Dress',
    brand: 'ASOS',
    price: 62,
    currency: 'AED',
    images: [img('swoon-dress-13')],
    category: 'dress',
    subcategory: 'midi',
    colors: ['champagne', 'black', 'dusty rose'],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    styleTags: ['elegant', 'occasion', 'satin', 'evening'],
    material: 'Satin Polyester',
    description: 'Fluid midi dress in liquid satin with a bias cut and thin adjustable straps.',
    isActive: true,
  },
  {
    id: 'item-14',
    name: 'Oversized Check Coat',
    brand: 'Toteme',
    price: 680,
    currency: 'AED',
    images: [img('swoon-coat-14')],
    category: 'outerwear',
    subcategory: 'coat',
    colors: ['camel check', 'grey check', 'black check'],
    sizes: ['XS', 'S', 'M', 'L'],
    styleTags: ['minimal', 'editorial', 'wool', 'oversized', 'luxury'],
    material: 'Wool-Alpaca Blend',
    description: 'Double-breasted oversized coat in a tonal check, lined in viscose.',
    isActive: true,
  },
  {
    id: 'item-15',
    name: 'Cotton T-Shirt Dress',
    brand: 'COS',
    price: 95,
    currency: 'AED',
    images: [img('swoon-dress-15')],
    category: 'dress',
    subcategory: 'midi',
    colors: ['off-white', 'black', 'blue'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    styleTags: ['minimal', 'casual', 'basics', 'cotton'],
    material: 'Organic Cotton',
    description: 'Relaxed T-shirt dress with a dropped hem and subtle side-seam pockets.',
    isActive: true,
  },
  {
    id: 'item-16',
    name: 'Linen Shirt Dress',
    brand: 'Arket',
    price: 145,
    currency: 'AED',
    images: [img('swoon-dress-16')],
    category: 'dress',
    subcategory: 'shirt',
    colors: ['white', 'ecru', 'sky blue'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    styleTags: ['minimal', 'linen', 'summer', 'casual', 'basics'],
    material: 'Linen',
    description: 'Unstructured shirt dress with a pointed collar, patch pockets, and a belted option.',
    isActive: true,
  },
  {
    id: 'item-17',
    name: 'Plissé Satin Skirt',
    brand: 'Ganni',
    price: 180,
    currency: 'AED',
    images: [img('swoon-skirt-17')],
    category: 'skirt',
    subcategory: 'midi',
    colors: ['dusty pink', 'sage', 'champagne'],
    sizes: ['XS', 'S', 'M', 'L'],
    styleTags: ['feminine', 'elegant', 'satin', 'occasion', 'midi'],
    material: 'Recycled Polyester Satin',
    description: 'Midi skirt with a permanent pleated finish and an elasticated waist.',
    isActive: true,
  },
  {
    id: 'item-18',
    name: 'Organic Ribbed Henley',
    brand: 'H&M',
    price: 29,
    currency: 'AED',
    images: [img('swoon-top-18')],
    category: 'top',
    subcategory: 'henley',
    colors: ['bone', 'charcoal', 'sage'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    styleTags: ['casual', 'basics', 'cotton', 'everyday'],
    material: 'Organic Cotton',
    description: 'Slim-fit ribbed henley with a three-button placket and long sleeves.',
    isActive: true,
  },
  {
    id: 'item-19',
    name: 'Suede Effect Mini Dress',
    brand: 'ASOS',
    price: 75,
    currency: 'AED',
    images: [img('swoon-dress-19')],
    category: 'dress',
    subcategory: 'mini',
    colors: ['rust', 'camel', 'black'],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    styleTags: ['casual', 'boho', 'autumn', 'mini'],
    material: 'Faux Suede',
    description: 'A-line mini dress in soft faux suede with button-down front and wide belt loops.',
    isActive: true,
  },
  {
    id: 'item-20',
    name: 'Oversized Blazer Dress',
    brand: 'Mango',
    price: 95,
    currency: 'AED',
    images: [img('swoon-dress-20')],
    category: 'dress',
    subcategory: 'blazer',
    colors: ['taupe', 'black', 'white'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    styleTags: ['minimal', 'office', 'tailored', 'elegant'],
    material: 'Polyester-Viscose Blend',
    description: 'Blazer-style dress with notched lapels, double breasted buttons, and a self-tie belt.',
    isActive: true,
  },
  {
    id: 'item-21',
    name: 'Ruched Jersey Top',
    brand: 'Zara',
    price: 28,
    currency: 'AED',
    images: [img('swoon-top-21')],
    category: 'top',
    subcategory: 'ruched',
    colors: ['dusty rose', 'black', 'cream'],
    sizes: ['XS', 'S', 'M', 'L'],
    styleTags: ['feminine', 'casual', 'jersey', 'summer'],
    material: 'Modal Jersey',
    description: 'Long-sleeved ruched top in soft jersey with a gathered side and cropped hem.',
    isActive: true,
  },
  {
    id: 'item-22',
    name: 'Relaxed Linen Shorts',
    brand: 'COS',
    price: 65,
    currency: 'AED',
    images: [img('swoon-shorts-22')],
    category: 'pants',
    subcategory: 'shorts',
    colors: ['ecru', 'khaki', 'slate'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    styleTags: ['minimal', 'linen', 'summer', 'casual'],
    material: '100% Linen',
    description: 'Mid-length linen shorts with a relaxed fit, side pockets, and a concealed fly.',
    isActive: true,
  },
];

export const MOCK_USERS: User[] = [
  {
    id: 'user-01',
    email: 'lea@example.com',
    username: 'lea.moreau',
    displayName: 'Léa Moreau',
    preferredSizes: ['S', '36 FR'],
    favouriteColors: ['cream', 'camel', 'sage'],
    preferredBrands: ['COS', 'Arket', 'Toteme'],
    location: 'Paris',
  },
  {
    id: 'user-02',
    email: 'mia@example.com',
    username: 'mia.chen',
    displayName: 'Mia Chen',
    preferredSizes: ['XS', 'S'],
    favouriteColors: ['blush', 'ivory', 'terracotta'],
    preferredBrands: ['Ganni', 'ASOS', 'H&M'],
    location: 'London',
  },
  {
    id: 'user-03',
    email: 'celine@example.com',
    username: 'celine.martin',
    displayName: 'Céline Martin',
    preferredSizes: ['M'],
    favouriteColors: ['sage', 'charcoal', 'rust'],
    preferredBrands: ['Zara', 'Mango', 'Sandro'],
    location: 'Lyon',
  },
];

const now = Date.now();

export const MOCK_MESSAGES: Message[] = [
  {
    id: 'msg-01',
    conversationId: 'conv-01',
    senderId: 'user-02',
    content: undefined,
    sharedItem: MOCK_ITEMS[0],
    createdAt: now - 120_000,
  },
  {
    id: 'msg-02',
    conversationId: 'conv-01',
    senderId: 'user-02',
    content: 'Would this linen coat go with the trousers I shared last week?',
    createdAt: now - 110_000,
  },
  {
    id: 'msg-03',
    conversationId: 'conv-02',
    senderId: 'user-03',
    content: 'Okay what about these three options for the bachelorette?',
    createdAt: now - 3_600_000,
  },
];

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: 'conv-01',
    participants: [MOCK_USERS[0], MOCK_USERS[1]],
    lastMessage: MOCK_MESSAGES[1],
    unreadCount: 2,
    isGroup: false,
    createdAt: now - 86_400_000,
  },
  {
    id: 'conv-02',
    participants: [MOCK_USERS[0], MOCK_USERS[1], MOCK_USERS[2]],
    lastMessage: MOCK_MESSAGES[2],
    unreadCount: 0,
    isGroup: true,
    groupName: 'Bachelorette planning',
    createdAt: now - 7 * 86_400_000,
  },
];
